owner: GameDiscoverCo
repo: uptime

assignees:
  - AviDuda

sites:
  - name: GameDiscoverCo Plus
    url: https://plus.gamediscover.co
  - name: GameDiscoverCo Console
    url: https://console.gamediscover.co
  - name: Company site
    url: https://gamediscover.co/
  - name: API
    url: $SHREDDER_STATUS_PAGE
  - name: Scraping
    url: $GARGON_PATH
    method: POST
    headers:
      - "Content-Type: application/x-www-form-urlencoded"
    body: "key=$SHREDDER_ADMIN_REST_API_KEY&process=ping"
  - name: Postman API documentation
    url: https://documenter.getpostman.com/view/4312055/UVRHi3Y4

status-website:
  cname: status.gamediscover.co
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GameDiscoverCo Status
  introTitle: "Status page for GameDiscoverCo infrastructure"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/GameDiscoverCo/uptime) for the infrastructure of [GameDiscoverCo](https://gamediscover.co/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: org-GameDiscoverCo-repo-uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
