# Change these first
owner: GameDiscoverCo # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: GameDiscoverCo Plus
    url: https://plus.gamediscover.co
  - name: GameDiscoverCo Console
    url: https://console.gamediscover.co
  - name: Company site
    url: https://gamediscover.co/
  - name: GameDiscoverCo API
    url: $SHREDDER_STATUS_PAGE
  - name: Postman API documentation
    url: https://documenter.getpostman.com/view/4312055/UVRHi3Y4

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gamediscover.co
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GameDiscoverCo Status
  introTitle: "Status page for GameDiscoverCo websites"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/GameDiscoverCo/uptime) for websites and infrastructure of [GameDiscoverCo](https://gamediscover.co/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
